/**
 *
 * $Id$
 */
package org.eclipse.cpsim.Diagram.validation;

import org.eclipse.cpsim.Diagram.CAR;
import org.eclipse.cpsim.Diagram.ECU;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.eclipse.cpsim.Diagram.CAN}.
 * This doesn't really do anything, and it's not a real EMF artifact. It was
 * generated by the org.eclipse.emf.examples.generator.validator plug-in to
 * illustrate how EMF's code generator can be extended. This can be disabled
 * with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CANValidator {
	boolean validate();

	boolean validateCarRef(CAR value);

	boolean validateEcuRefs(EList<ECU> value);

	boolean validateBandwidth(int value);

	boolean validateId(String value);

	boolean validateVersion(String value);

	boolean validateCanDB(String value);

	boolean validateIsCANFD(boolean value);
}
